Repository elias-sundqvist/DATX02-20-04, pull requests merged in 2020-03, with the labels that each got.

#9 Fixed midi loading and encoding
  src/midi_test.py
  src/preprocess.py
Labels: bug

#10 Midi decoding (from tensors to Mido) and saving now works
  src/midi_test.py
  src/preprocess.py
Labels: enhancement

#27 Add requirements.txt
  requirements.txt
Labels: enhancement

#29 Read hyperparameters from YAML file
  src/gan_example.py
  src/hparams.yaml
  src/util.py
Labels: enhancement

#35 Repo structure v2
  hparams/gan.yml
  hparams/vae.yml
  src/data/maestro.py
  src/data/midi.py
  src/data/nsynth.py
  src/data/process.py
  src/datasets/maestro.py
  src/gan_example.py
  src/generate.py
  src/losses.py
  src/model.py
  src/models/common/layers.py
  src/models/common/losses.py
  src/models/common/training.py
  src/models/gan/__init__.py
  src/models/gan/generate.py
  src/models/gan/model.py
  src/models/gan/train.py
  src/models/simple_gan.py
  src/models/vae.py
  src/models/vae/generate.py
  src/models/vae/model.py
  src/models/vae/train.py
  src/scripts/gen_tone.py
  src/test/midi_encoding.py
  src/train.py
  src/training.py
  src/util.py
  src/vae_example.py
Labels: enhancement, refactor

#47 Add conda environment file for Bayes computer
  environment.yml
Labels: enhancement
