Repository elias-sundqvist/DATX02-20-04, pull requests merged in 2020-04, with the labels that each got.

#52 Changed melspec to librosa function to fix inverse
  colab_import.sh
  hparams/transformer.yml
  hparams/transformer.yml.bak
  hparams/vae.yml
  requirements.txt
  src/__init__.py
  src/data/nsynth.py
  src/data/process.py
  src/evolve/__init__.py
  src/evolve/hparams.py
  src/evolve/hparams_test.py
  src/evolve/pool.py
  src/evolve/pool_test.py
  src/models/common/training.py
  src/models/gan/train.py
  src/models/transformer/generate.py
  src/models/transformer/preprocess.py
  src/models/transformer/train.py
  src/models/vae/generate.py
  src/models/vae/model.py
  src/models/vae/train.py
  src/test/spec_inverse.py
  src/train.py
Labels: bug

#56 Log/typofix
  docs/index.html
  docs/log.org
Labels: needs review

#50 Feat/transformer doc
  src/models/transformer/CustomLearningRateScheduler.png
  src/models/transformer/generate.py
  src/models/transformer/layers.py
  src/models/transformer/mask.py
  src/models/transformer/model.py
  src/models/transformer/optimizer.py
Labels: needs review

#58 [WIP] Aux classifier
  environment.yml
  hparams/gan.yml
  src/data/nsynth.py
  src/data/process.py
  src/models/gan/generate.py
  src/models/gan/model.py
  src/models/gan/train.py
  src/test/spec_inverse.py
Labels: WIP

#60 Create function for generating a note with tensorflow
  src/scripts/gen_tone.py
Labels: enhancement

#61 Log/lovisa edit in w12
  docs/log.org
Labels: needs review
